tone-row/flowchart-fun

src/App.tsx

Adds support for tab key raised in [this issue](https://github.com/tone-row/flowchart-fun/issues/2)

Tab key adds 2 spaces

---

src/App.tsx

Add original text in svg comment

---

src/App.tsx

Add bracket ids

---

src/App.tsx

Only run fit (and not layout) on resize

---

src/App.tsx

Fix loop for self reference edges

---

src/App.tsx

Don't render empty lines

---

src/App.tsx

Fix lines after multi-line comment

---

src/App.tsx

Show multiple edges between nodes

---

src/App.module.css
src/App.tsx

Adds hover effect for line number

---

src/App.module.css
src/App.tsx

Fix #57 
Preview downloaded JSON

Download Graph to Cytoscape JSON

---

app/src/App.module.css
app/src/App.tsx

Allow for expanding nodes

---

app/package.json
app/src/App.module.css
app/src/App.tsx
app/src/index.css
yarn.lock

Add ability to resize

---

app/src/App.module.css
app/src/App.tsx

Updates to box sizing

---

app/src/components/Graph.tsx

fix: share with question mark

---

app/src/utils.ts

Add ability to use label text as pointer

---

app/src/utils.ts

Hey there -- I am trying to add a feature (node background color via #123abc) and in the process of doing that I ended up refactoring some of the regular expression code so that it is all contained in one method and does not depend on if/elses
I hope this helps and if it does let me know if I can make it better / have any questions.
Thanks,
Pano

Refactoring regular expression code

---

app/src/components/Graph.tsx
app/src/components/ReadOnly.tsx
app/src/components/Router.tsx

feat: switch to hash for sharing

---

app/src/components/Graph.tsx
app/src/utils.ts

Fix hovered line number

---

app/package.json
app/src/components/Layout.tsx
app/src/components/Main.tsx
app/src/components/Router.tsx

Adds a fullscreen sharing mode under the `/f` path (similar to `/c` for compressed sharing)

feat: fullscreen share

---

.github/workflows/codecov.yml

Codecov action is failing without the secret.

Codecoverage failing. Don't

---

app/src/components/Graph.tsx

https://twitter.com/sribrahmana/status/1417498859786342400

fix app breaking on graph options issue

---

app/public/index.html

Change site title

---

.github/workflows/e2e.yml
app/.eslintrc.js
app/src/components/AppContext.tsx
app/src/components/Graph.tsx
app/src/components/useDownloadHandlers.ts
app/src/constants.ts

Support the `styles` key in frontmatter
Is appended to array of default styles and passed to `cy.json({ style })`

Support styles key from user

---

app/src/registerLanguage.ts

Fix syntax highlighting issue

---

app/src/lib/graphUtilityClasses.ts

feat(colors): add orange

---

app/src/components/Main.module.css
app/src/components/Main.tsx
app/src/components/MenuNext.module.css
app/src/components/MenuNext.tsx
app/src/components/ReadOnly.tsx
app/src/components/Router.tsx
app/src/components/TextResizer.module.css
app/src/lib/analytics.ts
app/src/lib/helpers.ts
app/src/lib/hooks.ts

Added a button to quickly create a copy to read only edit screen and fullscreen

Replace rename button with copy button on read-only page

---

app/src/components/Docs.tsx
app/src/components/MenuNext.tsx

chore(qa): fix toc; copy button text

---

app/package.json
app/src/components/Graph.tsx
app/src/components/ShareDialog.module.css
app/src/components/ShareDialog.tsx
app/src/components/Shared.tsx
app/src/lib/graphUtilityClasses.ts
app/src/lib/mermaid.test.ts
app/src/lib/mermaid.ts
app/src/lib/store.graph.ts
app/src/lib/utils.ts
pull_request_template.md
yarn.lock

feat: exporting to mermaid js syntax

---

app/src/components/Public.tsx
app/src/components/ReadOnly.tsx

fix(export): comments in yaml

---

app/src/lib/utils.test.ts
app/src/lib/utils.ts

fix: rendering bugs

---

app/src/components/Navigation.module.css
app/src/components/Navigation.tsx

feat(sponsors): large cta

---

app/src/components/ShareDialog.tsx

fix(share): link copied on click; full value

---

app/src/lib/themes/eggs.ts

fix(eggs): looping labels

---

app/src/components/Graph.tsx
app/src/components/Main.tsx
app/src/lib/parseText.test.ts
app/src/lib/parseText.ts
app/src/pages/Edit.tsx
app/src/pages/EditUserChart.tsx
app/src/pages/Help.tsx
app/src/pages/Public.tsx
app/src/pages/ReadOnly.tsx

fix(parse): link by line number w/ yaml

---

app/e2e/main.spec.ts
app/src/components/Sponsor.tsx

chore(e2e): add sign up test

---

app/src/pages/EditUserChart.module.css
app/src/pages/EditUserChart.tsx

fix(ui): expand text under hosted indicator

---

app/package.json
app/src/components/AppContext.tsx
app/src/components/Graph.tsx
app/src/components/GraphOptionsBar.tsx
app/src/components/Sponsor.tsx
app/src/lib/constants.ts
app/src/lib/cytoscape.ts
app/src/lib/graphOptions.ts
app/src/lib/preprocessGraphLayout.ts
app/src/lib/useUpdateGraphOptionsText.ts
app/src/pages/Edit.tsx
app/src/pages/EditUserChart.tsx
app/src/pages/Help.tsx
app/src/react-app-env.d.ts
yarn.lock

feat(layouts): add elk layouts, sponsor-only

---

app/api/validate.js
app/src/components/LoginForm.module.css

fix(login): yearly

---

app/src/components/Main.tsx
app/src/components/MenuNext.tsx
app/src/lib/hooks.ts

fix(public): clone button on public charts

---

.github/workflows/e2e.yml
app/api/create-customer.js
app/e2e/auth.spec.ts
app/e2e/index.spec.ts
app/e2e/utils.ts
app/playwright.config.ts
app/src/components/Sponsor.tsx
app/src/pages/Edit.tsx

fix(signup): prevent customer creation b4 card verify

---

app/src/lib/graphUtilityClasses.ts
app/src/lib/mermaid.ts
app/src/lib/themes/blokus.ts
app/src/lib/themes/clay.ts
app/src/lib/themes/eggs.ts
app/src/lib/themes/excalidraw.ts
app/src/lib/themes/monospace.ts
app/src/lib/themes/museum.ts
app/src/lib/themes/original-dark.ts
app/src/lib/themes/original.ts
app/src/lib/themes/playbook.ts

feat(themes): adjust colors to match

---

app/src/components/Router.tsx
app/src/pages/New.tsx

feat(routes): 'n' for new chart route

---

app/src/components/Graph.tsx
app/src/components/Main.tsx
app/src/lib/parseText.test.ts
app/src/lib/parseText.ts
app/src/pages/Edit.tsx
app/src/pages/EditHosted.tsx
app/src/pages/Help.tsx
app/src/pages/Public.tsx
app/src/pages/ReadOnly.tsx

fix(app): hovering nodes when metadata

---

app/src/lib/mermaid.test.ts
app/src/lib/mermaid.ts

fix: escape mermaid html entities

---

app/src/lib/useGetSize.ts

fix(nodesize): fix multiline text

---

app/src/lib/constants.ts

feat(editor): show indentation guides

---

app/src/components/Navigation.tsx
app/src/lib/themes/blokus.ts
app/src/lib/themes/monospace.ts
app/src/lib/useGetSize.ts

fix(graph): circle not a circle

---

app/api/customer-info.js

fix(sponsors): add legacy stripe price

---

.github/workflows/e2e.yml
README.md
app/e2e/unauth.spec.ts
app/e2e/utils.ts
app/package.json
app/playwright.config.ts
app/src/components/GraphContextMenu.tsx
app/src/components/ShareDialog.tsx
app/src/components/useDownloadHandlers.ts
app/src/pages/New.test.tsx
app/tsconfig.json
pnpm-lock.yaml

add padding to exported images

---

app/src/components/AppContext.test.tsx
app/src/components/AppContext.tsx
app/src/components/Navigation.tsx
app/src/lib/queries.ts
app/src/pages/New.tsx

feat(sponsors): prefetch sponsor charts to avoid loading flash

---

app/public/index.html

fix(preload): rm monaco preload; add fira font preload

---

app/src/locales/de/messages.po
app/src/locales/en/messages.po
app/src/locales/fr/messages.po
app/src/locales/hi/messages.po
app/src/locales/ko/messages.po
app/src/locales/pt-br/messages.po
app/src/locales/zh/messages.po

fix(i18n): file number change

---

app/src/components/Graph.module.css
app/src/components/GraphFloatingMenu.css
app/src/components/GraphFloatingMenu.tsx
app/src/components/GraphOptionsBar.module.css
app/src/components/GraphOptionsBar.tsx
app/src/components/GraphWrapper.module.css
app/src/components/GraphWrapper.tsx
app/src/components/IconButton.module.css
app/src/components/IconButton.tsx

feat(controls): add floating graph menu

---

app/e2e/auth.spec.ts
app/src/components/Navigation.tsx
app/src/components/Sponsor.tsx
app/src/locales/de/messages.js
app/src/locales/de/messages.po
app/src/locales/en/messages.js
app/src/locales/en/messages.po
app/src/locales/fr/messages.js
app/src/locales/fr/messages.po
app/src/locales/hi/messages.js
app/src/locales/hi/messages.po
app/src/locales/ko/messages.js
app/src/locales/ko/messages.po
app/src/locales/pt-br/messages.js
app/src/locales/pt-br/messages.po
app/src/locales/zh/messages.js
app/src/locales/zh/messages.po

feat(price): lower price

---

api/customer-info.js
api/validate.js

fix(prices): log in with all prices

---

app/package.json
app/src/lib/constants.ts
pnpm-lock.yaml

feat(menu): remove unused monaco context menu

---

app/src/components/AppContext.tsx
app/src/components/CurrentTab.tsx
app/src/components/GraphOptionsBar.tsx
app/src/components/Layout.tsx
app/src/components/Navigation.tsx
app/src/components/Router.tsx
app/src/components/SharedHeader.tsx
app/src/components/Sponsor.tsx
app/src/components/SponsorDashboard.tsx
app/src/lib/graphOptions.ts
app/src/lib/hooks.ts

feat(sponsor): give page it's own route

---

app/src/components/Router.tsx
app/src/components/ShareDialog.tsx
app/src/lib/hooks.ts
app/src/lib/queries.ts
app/src/lib/useHostedDoc.ts
app/src/pages/Charts.tsx
app/src/pages/EditHosted.tsx
app/src/pages/New.tsx

fix(navigation): bugs with hosted charts, new and back button

---

app/package.json
app/src/components/SharedHeader.tsx
pnpm-lock.yaml
shared/header.css

fix(docs): scrolling on mobile safari

---

app/src/components/Shared.module.css
app/src/components/Shared.tsx
app/src/components/SharedHeader.tsx

fix(ui): input with min font-size for phones

---

app/src/components/SponsorDashboard.module.css
app/src/components/SponsorDashboard.tsx
app/src/locales/de/messages.js
app/src/locales/de/messages.po
app/src/locales/en/messages.js
app/src/locales/en/messages.po
app/src/locales/fr/messages.js
app/src/locales/fr/messages.po
app/src/locales/hi/messages.js
app/src/locales/hi/messages.po
app/src/locales/ko/messages.js
app/src/locales/ko/messages.po
app/src/locales/pt-br/messages.js
app/src/locales/pt-br/messages.po
app/src/locales/zh/messages.js
app/src/locales/zh/messages.po

feat(sponsor): add link to stripe dashboard

---

api/package.json
app/e2e/monthly.spec.ts
app/src/components/ShareDialog.tsx
pnpm-lock.yaml

fix(public): fix public charts and add e2e test to confirm

---

app/public/index.html

chore(analytics): add optimize

---

app/src/lib/analytics.ts

fix(a7s): fix routing analtyics

---

app/src/components/SharedHeader.tsx

chore(a7s): track clicks to sponsor page

---

app/src/components/SharedHeader.tsx

fix(sponsor): change sponsor link to client-side link

---

app/e2e/monthly.spec.ts
app/public/index.html
app/src/components/Graph.tsx
app/src/components/GraphContextMenu.tsx
app/src/components/GraphOptionsBar.tsx
app/src/components/ShareDialog.tsx
app/src/components/SharedHeader.tsx
app/src/lib/analytics.ts
app/src/lib/graphOptions.ts
app/src/pages/Charts.tsx
app/src/pages/New.tsx

chore(a7s): remove UA4 and optimize in favor of GTM

---

app/e2e/auth.spec.ts
app/e2e/monthly.spec.ts
app/src/components/Router.test.tsx
app/src/components/SharedHeader.tsx
app/src/locales/de/messages.js
app/src/locales/de/messages.po
app/src/locales/en/messages.js
app/src/locales/en/messages.po
app/src/locales/fr/messages.js
app/src/locales/fr/messages.po
app/src/locales/hi/messages.js
app/src/locales/hi/messages.po
app/src/locales/ko/messages.js
app/src/locales/ko/messages.po
app/src/locales/pt-br/messages.js
app/src/locales/pt-br/messages.po
app/src/locales/zh/messages.js
app/src/locales/zh/messages.po
app/src/pages/Sponsor.tsx

feat(copy): pricing over sponsorship

---

app/package.json
app/src/components/Graph.tsx
app/src/lib/parsers.ts
app/src/lib/themes/blokus.ts
app/src/lib/themes/clay.ts
app/src/lib/themes/comic-book.ts
app/src/lib/themes/cyberpunk.ts
app/src/lib/themes/eggs.ts
app/src/lib/themes/excalidraw.ts
app/src/lib/themes/futuristic.ts
app/src/lib/themes/monospace.ts
app/src/lib/themes/museum.ts
app/src/lib/themes/original-dark.ts
app/src/lib/themes/original.ts
app/src/lib/themes/playbook.ts
app/src/lib/themes/retro.ts
pnpm-lock.yaml

feat(parser): user can enable graph-selector

---

app/e2e/unauth.spec.ts
app/package.json
app/src/components/Tabs/EditLayoutTab.tsx
app/src/lib/graphOptions.ts
app/src/lib/parsers.ts
app/src/pages/Edit.module.css
pnpm-lock.yaml

feat(syntax): add toggle for syntax choice

---

blog/src/components/niceData.ts
blog/src/layouts/BlogPost.astro
blog/src/layouts/Layout.astro
blog/src/pages/index.astro
blog/src/pages/post/graph-selector-update-january-2023.mdx
blog/src/pages/post/graph-syntax-css-selector.mdx
blog/src/pages/post/hello-world.mdx

feat(blog): add update post about syntax migration

---

app/package.json
pnpm-lock.yaml

feat(gs): update gs version

---

app/src/components/SponsorDashboard.module.css
app/src/components/SponsorDashboard.tsx
app/src/lib/queries.ts

fix(sponsor): dates on account page

---

app/src/components/Graph.tsx

fix(theme): fix missing theme on tab switch

---

app/src/components/Graph.tsx

fix(graph): zoom does not change on dragfree

---

app/e2e/graph-floating-menu.spec.ts
app/src/components/GraphFloatingMenu.css
app/src/components/GraphFloatingMenu.module.css
app/src/components/GraphFloatingMenu.tsx

feat(graphmenu): add zoom buttons

---

app/src/components/GraphFloatingMenu.tsx
app/src/components/MightLoseWarning.tsx
app/src/components/SharedHeader.tsx
app/src/lib/track.ts
app/src/locales/de/messages.js
app/src/locales/de/messages.po
app/src/locales/en/messages.js
app/src/locales/en/messages.po
app/src/locales/fr/messages.js
app/src/locales/fr/messages.po
app/src/locales/hi/messages.js
app/src/locales/hi/messages.po
app/src/locales/ko/messages.js
app/src/locales/ko/messages.po
app/src/locales/pt-br/messages.js
app/src/locales/pt-br/messages.po
app/src/locales/zh/messages.js
app/src/locales/zh/messages.po

feat(track): might lose warning

---

app/src/components/EditorWrapper.tsx
app/src/components/MightLoseSponsorTrigger.tsx
app/src/components/MightLoseWarning.tsx
app/src/locales/de/messages.js
app/src/locales/fr/messages.js
app/src/locales/hi/messages.js
app/src/locales/ko/messages.js
app/src/locales/pt-br/messages.js
app/src/locales/zh/messages.js

fix(i18n): compile missing translations

---

app/package.json
pnpm-lock.yaml

feat(pointer): autocomplete

---

app/src/components/GraphContextMenu.module.css
app/src/components/GraphContextMenu.tsx
app/src/lib/graphUtilityClasses.ts

feat(ctx): add size and border

---

app/src/pages/Charts.tsx

fix(hosted): deleting hosted chart stays on charts page

---

app/e2e/auth.spec.ts
app/e2e/unauth.spec.ts
app/src/components/EditorWrapper.module.css
app/src/components/EditorWrapper.tsx
app/src/components/RenameButton.tsx
app/src/lib/queries.ts
app/src/slang/config.ts

fix(hosted): renaming hosted chart now updates interface

---

app/src/components/Header.tsx
app/src/components/LoginForm.module.css
app/src/components/LoginForm.tsx
app/src/index.css
app/src/pages/LogIn.module.css
app/src/pages/LogIn.tsx

fix(mobile): login link on mobile

---

app/package.json
app/src/components/GraphContextMenu.tsx
app/src/components/ShareDialog.tsx
app/src/lib/logsnag.ts
pnpm-lock.yaml

feat(user): LogSnag Integration

---

app/src/components/GraphFloatingMenu.tsx
app/src/components/Tabs/EditLayoutTab.tsx
app/src/lib/useIsFrozen.ts

- Add the unfreeze button to the floating menu when chart is frozeen
https://user-images.githubusercontent.com/6456756/218238687-c8399a06-b7f8-4e10-b63d-2f805ab09832.mp4

feat: unfreeze button on floating menu 

---

app/src/pages/New.tsx

fix: New mobile styles

---

app/src/components/Graph.tsx
app/src/components/GraphContextMenu.tsx
app/src/lib/graphUtilityClasses.ts

Drag to Select Multiple Nodes

---

app/src/pages/New.tsx

feat: default title for chart

---

api/_lib/_helpers.ts
api/_lib/_openai.ts
api/_lib/_stripe.ts
api/_lib/_supabase.ts
api/jest.config.js
api/package.json
api/prompt/_parseFlowchart.test.ts
api/prompt/_parseFlowchart.ts
api/prompt/extract.ts
api/prompt/instruct.ts
app/e2e/auth.spec.ts
app/package.json
app/src/lib/getDefaultChart.ts
app/src/lib/queries.ts
app/src/locales/de/messages.js
app/src/locales/de/messages.po
app/src/locales/en/messages.js
app/src/locales/en/messages.po
app/src/locales/fr/messages.js
app/src/locales/fr/messages.po
app/src/locales/hi/messages.js
app/src/locales/hi/messages.po
app/src/locales/ko/messages.js
app/src/locales/ko/messages.po
app/src/locales/pt-br/messages.js
app/src/locales/pt-br/messages.po
app/src/locales/zh/messages.js
app/src/locales/zh/messages.po
app/src/pages/New.tsx
pnpm-lock.yaml

Add Basic Prompting for New Charts

---

app/package.json
app/src/components/Graph.tsx
app/src/components/RenameButton.tsx
app/src/components/Tabs/EditLayoutTab.tsx
app/src/components/Tabs/shared.tsx
app/src/lib/constants.ts
app/src/lib/getLayout.test.ts
app/src/lib/getLayout.ts
app/src/lib/mermaid.test.ts
app/src/lib/useGraphStore.ts
app/src/react-app-env.d.ts
pnpm-lock.yaml

Improve CoSE

---

api/prompt/_parseFlowchart.test.ts
api/prompt/_parseFlowchart.ts

Fix Prompt Bug

---

api/version.ts
app/package.json
app/src/components/Layout.tsx
app/src/components/Shared.module.css
app/src/components/SyntaxReference.module.css
app/src/components/VersionCheck.tsx
app/src/lib/versionCheck.ts
app/src/locales/de/messages.js
app/src/locales/de/messages.po
app/src/locales/en/messages.js
app/src/locales/en/messages.po
app/src/locales/fr/messages.js
app/src/locales/fr/messages.po
app/src/locales/hi/messages.js
app/src/locales/hi/messages.po
app/src/locales/ko/messages.js
app/src/locales/ko/messages.po
app/src/locales/pt-br/messages.js
app/src/locales/pt-br/messages.po
app/src/locales/zh/messages.js
app/src/locales/zh/messages.po
pnpm-lock.yaml

- feat: ask for refresh on new version
- chore: missing i18n

Refresh on New Version

---

app/src/components/SignUpForm.tsx
app/src/components/TextEditor.tsx
app/src/lib/queries.ts

Fix New User / Dark Color Scheme Bug

---

README.md
app/src/components/Header.tsx

Update Discord Link

---

app/e2e/auth.spec.ts
app/e2e/openExportDialog.ts
app/e2e/unauth.spec.ts
app/src/components/GraphContextMenu.tsx
app/src/components/Header.css
app/src/components/MightLoseSponsorTrigger.tsx
app/src/components/ShareDialog.tsx
app/src/components/Shared.module.css
app/src/components/SvgProOnlyPopover.tsx
app/src/locales/de/messages.js
app/src/locales/de/messages.po
app/src/locales/en/messages.js
app/src/locales/en/messages.po
app/src/locales/fr/messages.js
app/src/locales/fr/messages.po
app/src/locales/hi/messages.js
app/src/locales/hi/messages.po
app/src/locales/ko/messages.js
app/src/locales/ko/messages.po
app/src/locales/pt-br/messages.js
app/src/locales/pt-br/messages.po
app/src/locales/zh/messages.js
app/src/locales/zh/messages.po
app/src/pages/Pricing.tsx

- Add SVG Pro User Hovercard
- Add translations

Make SVG Pro Only

---

app/src/components/EditorWrapper.module.css
app/src/components/EditorWrapper.tsx
app/src/pages/Charts.tsx

Charts Page Design Notes

---

app/src/components/EditorWrapper.module.css
app/src/components/Graph.tsx
app/src/lib/hooks.ts
app/src/lib/parsers.ts
app/src/pages/Edit.tsx
app/src/pages/EditHosted.tsx

Changing Graphs Keeps Remnants of Graph Open Before

---

app/src/components/ShareDialog.tsx

Bug: Cannot export v1 parser

---

app/package.json
app/src/components/GraphContextMenu.module.css
app/src/components/GraphContextMenu.tsx
app/src/lib/graphUtilityClasses.ts
pnpm-lock.yaml

Enable edge context menu

---

README.md
app/src/lib/getGetSize.ts

- Fix Diamond Shape
- Update README

Fix Diamond Shape

---

app/package.json
app/src/components/LearnSyntaxDialog.tsx
app/src/lib/getGetSize.ts
app/src/lib/graphUtilityClasses.ts
app/src/locales/de/messages.js
app/src/locales/de/messages.po
app/src/locales/en/messages.js
app/src/locales/en/messages.po
app/src/locales/fr/messages.js
app/src/locales/fr/messages.po
app/src/locales/hi/messages.js
app/src/locales/hi/messages.po
app/src/locales/ko/messages.js
app/src/locales/ko/messages.po
app/src/locales/pt-br/messages.js
app/src/locales/pt-br/messages.po
app/src/locales/zh/messages.js
app/src/locales/zh/messages.po
pnpm-lock.yaml

- Add right rhomboid
- Add translations
- compile translations
- Fix mermaid export

Add right rhomboid

---

app/src/components/PaymentStepper.tsx
app/src/locales/de/messages.js
app/src/locales/de/messages.po
app/src/locales/en/messages.js
app/src/locales/en/messages.po
app/src/locales/fr/messages.js
app/src/locales/fr/messages.po
app/src/locales/hi/messages.js
app/src/locales/hi/messages.po
app/src/locales/ko/messages.js
app/src/locales/ko/messages.po
app/src/locales/pt-br/messages.js
app/src/locales/pt-br/messages.po
app/src/locales/zh/messages.js
app/src/locales/zh/messages.po

Tweak Payment Step Copy

---

app/package.json
app/src/components/LearnSyntaxDialog.tsx
app/src/components/TextResizer.module.css
app/src/lib/themes/blokus.ts
app/src/lib/themes/comic-book.ts
app/src/lib/themes/eggs.ts
app/src/lib/themes/excalidraw.ts
app/src/lib/themes/futuristic.ts
app/src/lib/themes/monospace.ts
app/src/lib/themes/original-dark.ts
app/src/lib/themes/original.ts
app/src/lib/themes/retro.ts
pnpm-lock.yaml

- Remember Learn Syntax Scroll Position
- Update graph-selector

Remember Learn Syntax Scroll Position

---

app/src/components/PaymentStepper.tsx
app/src/pages/Pricing.tsx

Improve Pricing Page Dark Mode

---

app/e2e/auth.spec.ts
app/src/locales/de/messages.js
app/src/locales/de/messages.po
app/src/locales/en/messages.js
app/src/locales/en/messages.po
app/src/locales/fr/messages.js
app/src/locales/fr/messages.po
app/src/locales/hi/messages.js
app/src/locales/hi/messages.po
app/src/locales/ko/messages.js
app/src/locales/ko/messages.po
app/src/locales/pt-br/messages.js
app/src/locales/pt-br/messages.po
app/src/locales/zh/messages.js
app/src/locales/zh/messages.po
app/src/pages/LogIn.tsx
app/src/pages/New.tsx

- Change Standard for Persistent
- Change Start for Getting Started
- Move errors closer to problem
- Small copy change on Log In page
- Add autoanimate to New page

New Flowchart Page Clarification

---

app/src/lib/getFunFlowchartName.tsx
app/src/pages/New.tsx

Fun Default Flowchart Names

---

app/src/locales/de/messages.js
app/src/locales/de/messages.po
app/src/locales/en/messages.js
app/src/locales/en/messages.po
app/src/locales/fr/messages.js
app/src/locales/fr/messages.po
app/src/locales/hi/messages.js
app/src/locales/hi/messages.po
app/src/locales/ko/messages.js
app/src/locales/ko/messages.po
app/src/locales/pt-br/messages.js
app/src/locales/pt-br/messages.po
app/src/locales/zh/messages.js
app/src/locales/zh/messages.po
app/src/pages/New.tsx
app/src/pages/post/Post.css
app/src/pages/post/Post.tsx

Improved Create From Prompt Suggestions

---

app/src/components/ThemePicker.tsx
app/src/lib/preprocessCytoscapeStyle.ts
app/src/lib/themes/futuristic.ts

Fix Font Loading

---

app/src/components/Graph.tsx
app/src/components/GraphFloatingMenu.tsx
app/src/lib/useGraphStore.ts
app/src/locales/de/messages.js
app/src/locales/de/messages.po
app/src/locales/en/messages.js
app/src/locales/en/messages.po
app/src/locales/fr/messages.js
app/src/locales/fr/messages.po
app/src/locales/hi/messages.js
app/src/locales/hi/messages.po
app/src/locales/ko/messages.js
app/src/locales/ko/messages.po
app/src/locales/pt-br/messages.js
app/src/locales/pt-br/messages.po
app/src/locales/zh/messages.js
app/src/locales/zh/messages.po
app/src/ui/Shared.tsx

Toggle to Disable Zoom Lock

---

app/src/components/Graph.tsx
app/src/components/GraphFloatingMenu.tsx
app/src/components/ImportDataDialog.tsx
app/src/components/ImportDataUnauthenticatedDialog.tsx
app/src/components/MightLoseSponsorTrigger.tsx
app/src/components/MightLoseWarning.tsx
app/src/components/Tabs/EditStyleTab.tsx
app/src/components/downloads.ts
app/src/locales/de/messages.js
app/src/locales/de/messages.po
app/src/locales/en/messages.js
app/src/locales/en/messages.po
app/src/locales/fr/messages.js
app/src/locales/fr/messages.po
app/src/locales/hi/messages.js
app/src/locales/hi/messages.po
app/src/locales/ko/messages.js
app/src/locales/ko/messages.po
app/src/locales/pt-br/messages.js
app/src/locales/pt-br/messages.po
app/src/locales/zh/messages.js
app/src/locales/zh/messages.po
app/src/pages/Edit.tsx
app/src/pages/EditHosted.tsx

- Remove Comments
- Lazy Load a Few Things

Remove Comments

---

app/src/components/InfoHeader.tsx
app/src/index.tsx
app/src/pages/post/Post.css

Fix Single Post CSS

---

app/src/components/Header.tsx

No Mobile Link To Homepage

---

api/package.json
app/package.json
app/src/lib/preprocessCytoscapeStyle.ts
pnpm-lock.yaml

Fix White Screen Bug

---

app/src/components/ShareDialog.tsx

Fix Chinese Character CSV Export Bug

---

app/src/components/Graph.module.css
app/src/components/Graph.tsx
app/src/components/GraphFloatingMenu.tsx
app/src/components/GraphWrapper.module.css
app/src/components/GraphWrapper.tsx
app/src/pages/Edit.tsx
app/src/pages/EditHosted.tsx

Border and Padding to Graph

---

app/e2e/unauth.spec.ts
app/src/components/Feedback.tsx
app/src/components/Header.tsx
app/src/components/Settings.tsx

Feedback Button in Nav Bar

---

app/src/components/Graph.tsx
app/src/lib/useGraphStore.ts

Reset zoom when arriving on Edit

---

app/package.json
app/src/components/Graph.tsx
app/src/components/GraphContextMenu.tsx
app/src/lib/cytoscape.ts
app/src/lib/preprocessCytoscapeStyle.ts
app/src/react-app-env.d.ts
pnpm-lock.yaml

- Add dynamic classes for childless nodes
- Find parent and edge dynamic classes
- Add snap-to-grid

Dynamic Class Selector

---

app/src/components/Graph.tsx

Fix New Flowchart AutoFit Not Reset

---

app/src/components/Layout.module.css
app/src/components/Tabs/EditorTabList.module.css
app/src/components/Tabs/EditorTabList.tsx
app/src/lib/useTabsStore.ts
app/src/pages/Edit.tsx
app/src/pages/EditHosted.tsx

Setup Tabs

---

api/loops-event.ts
app/src/components/PaymentStepper.tsx
app/src/lib/sendLoopsEvent.ts
app/src/pages/Account.tsx

Add Loops Integration

---

app/src/locales/es/messages.po

Fix Flujograma Spanish Translation

---

api/customer-info.ts

Sort Active Subscriptions

---

app/src/components/AuthWall.tsx
app/src/components/Router.tsx
app/src/lib/useSupportLegacyNRoute.ts
app/src/pages/Charts.tsx
app/src/pages/ReadOnly.tsx

Fix New Link from Charts Page

---

app/src/lib/sendLoopsEvent.ts
app/src/pages/Success.tsx

Fix New Subscriber Email

---

app/src/lib/sendLoopsEvent.ts

Add Loops Transparency

---

app/src/components/AppContextProvider.tsx
app/src/components/EditWrapper.tsx
app/src/components/Graph.tsx
app/src/components/MobileTabToggle.tsx
app/src/lib/useEditorStore.ts
app/src/lib/useMobileStore.ts

- Basic jump to line in editor
- Move mobile tab state into zustand
- Toggle tab if necessary before focusing

Double-Clicking Node Jumps Cursor to Relevant Text

---

api/_lib/_llm.ts
api/prompt/edit.ts
app/src/components/EditWithAI.tsx

Inline AI Improvements

---

app/src/components/LoadTemplateDialog.tsx
app/src/components/VersionCheck.tsx

- Smarter Template Content Loading
- Fix reload to update z-index bug
- Fix show modal logic

Smarter Template Content Loading

---

api/_lib/_helpers.ts
api/customer-info.ts
app/src/lib/hooks.ts

Hotfix Trial Access

---

app/src/components/Graph.tsx
app/src/lib/hooks.ts

Remove Animation

---

app/src/components/CloneButton.tsx
app/src/components/EditWithAI.tsx
app/src/components/FlowchartHeader.tsx
app/src/components/ImportDataDialog.tsx
app/src/components/LearnSyntaxDialog.tsx
app/src/components/LoadFileButton.tsx
app/src/components/LoadTemplateDialog.tsx
app/src/components/RenameButton.tsx
app/src/components/ShareDialog.tsx
app/src/components/Tabs/EditorTabList.tsx
app/src/ui/EditorActionTextButton.tsx

Instrument Tier 1

---

api/prompt/convert.ts
app/package.json
app/src/lib/convertToFlowchart.ts
pnpm-lock.yaml

- **Fix stream parsing bug**
- **Increase conversion limits**

Fix Conversion Stream Parse Bug

---

app/src/components/AiToolbar.tsx
app/src/components/ConvertToFlowchart.tsx
app/src/components/TextEditor.tsx
app/src/lib/sanitizeOnPaste.test.ts
app/src/lib/sanitizeOnPaste.ts
app/src/lib/useEditorStore.ts

Sanitize User Text on Paste

---

app/src/pages/New.tsx

Add example prompts for 'Use AI' feature on new page

---

app/src/components/ConvertOnPasteOverlay.tsx
app/src/components/TextEditor.tsx

Don't show conversion overlay on run

---

app/src/components/GraphFloatingMenu.tsx
app/src/components/getNodePositionsFromCy.tsx
app/src/lib/alignNodes.ts

Implement Automatic Node Alignment

---

api/prompt/_shared.ts

Free generations costly

---

app/package.json
pnpm-lock.yaml

Highlighting Edge Labels with Special Characters

---

app/src/lib/getSize.ts

Resizer Bug

---

app/src/components/LoadTemplateDialog.tsx
app/src/lib/loadTemplate.ts

Load template disables css only

---

app/src/components/PaywallModal.tsx
app/src/lib/usePaywallModalStore.ts

Update Button Text Wrapping

---

api/prompt/_shared.ts

Adjust Ratelimit

---

app/src/components/AiToolbar.tsx

Disable Edit Button for Default Flowchart

---

api/prompt/_shared.ts
app/package.json
app/src/lib/getElements.ts
pnpm-lock.yaml

- **Update browserlist**
- **Upgrade posthog**

Update browserlist db & posthog

---

app/src/components/Layout.tsx

Hotfix: Supabase down

---

app/src/components/Layout.tsx

Remove banner
